### PR TITLE
Add parallelism parameter

### PR DESCRIPTION
**Pull request by alexwilcox9**
Hi @ljfranklin 
Is this the right way to go about resolving https://github.com/ljfranklin/terraform-resource/issues/139?
docker-build seems to run fine but I haven't tested this yet and will do so later in the week

Cheers
Alex

### CODE REVIEW

**Comment by ljfranklin** [comment]
Thanks for taking a look! Implementation looks fine to me. Normally I'd want a test added but I can't think of a way to write a meaningful integration test for this feature. Let me know when you've manually verified it works for you and I'll get it merged.

**Comment by alexwilcox9** [comment]
Testing so far hasn't been all that promising. When I set parallelism to 1 terraform still appears to be doing things concurrently, I was expecting it to slow down and wait until the current resource has deployed before starting on the next.
To be certain it was reading the parameter at all I fed it a string which caused an error so that's definitely working however it's like the arg still isn't being set

Any ideas? Is there anywhere else this argument would need to be added in order for it to work?

**Comment by ljfranklin** [comment]
Ah, you probably also need to add that field to [model.Merge](https://github.com/ljfranklin/terraform-resource/blob/cadaa3ce340ed59b0fef24e3ff3e495bcd57119f/src/terraform-resource/models/terraform.go#L47). If that still doesn't work you can try adding `source.env.TF_LOG: DEBUG` to get more verbose logging.

**Comment by alexwilcox9** [comment]
Not sure how I missed that! That worked a treat, I tried this on my dev pipeline with it set to one and it ran much slower as expected
I've also added a couple lines to the readme :)

**Comment by ljfranklin** [comment]
Thanks for the PR @alexwilcox9! This change is moving through my CI pipeline now and should be available in `ljfranklin/terraform-resource:latest` and `ljfranklin/terraform-resource:0.15.5` shortly.

**Pull request merged**
