### PR TITLE
support optional plugin_dir

### PR DESCRIPTION
**Pull request by peterellisjones**
This adds an optional parameter to the PUT operation that allows you to specify a local plugin dir which is useful if you want to use third-party plugins.

Note that (annoyingly) terraform will not allow you to use _both_ a local plugin dir (using `-plugin-dir` and fetch plugins from the internet (using `-get-plugins=true`). If you specify `-plugin-dir`, it will ignore `-get-plugins=true` and fail if _any_ required plugins are missing. This means that to use this parameter, you have to go and download all your standard plugins from https://releases.hashicorp.com/ as well as the third-party plugins you wanted to use.

This is terrible UX so feel free to reject the PR on those grounds :) — Sadly I don't have an option as I need to use third-party plugins so am making this PR in case you want this feature. I've tested it and am using it as part of my current CI pipelines.

### CODE REVIEW

**Comment by ljfranklin** [comment]
@peterellisjones thanks for submitting this PR! Sounds like a useful feature, but before merging could you add an integration test so we can see this working end to end? You can either add a test to [out_test.go](https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/out/out_test.go) or create a new test file beside it called `out_plugin_test.go` or similar. You'll have to add a new template that requires custom plugins in [fixtures](https://github.com/ljfranklin/terraform-resource/tree/master/fixtures) as well. Let me know if you run into issues with the test setup, you can find more instructions [here](https://github.com/ljfranklin/terraform-resource/blob/master/DEVELOPMENT.md).

When you say you need to fetch all the plugins manually, does your template have a mix of built-in plugins and custom plugins? Have you opened an issue on [Terraform](https://github.com/hashicorp/terraform/issues) to see if this is something they'd be willing to fix?

**Comment by peterellisjones** [comment]
@ljfranklin cool I'll try and build an integration test.

I can't find an issue for the `-plugin-dir` / `-get-plugins` behaviour in the terraform github repo but the terraform cli help for the init command is pretty clear:

```
-plugin-dir          Directory containing plugin binaries. This overrides all
                       default search paths for plugins, and prevents the
                       automatic installation of plugins. This flag can be used
                       multiple times.
```

My guess is that `-plugin-dir` is really "offline-mode" for most people so no one is expecting to also be able to download the standard plugins

**Comment by ljfranklin** [comment]
@peterellisjones looks like the Terraform team is aware of the issue and tracking it https://github.com/hashicorp/terraform/issues/15997 and https://github.com/hashicorp/terraform/issues/15801

**Comment by peterellisjones** [comment]
Hi @ljfranklin, I've just added integration tests for this. I did this by copying the lifecycle tests and plan tests and stripping away a lot of the minor assertions to avoid too much duplication. It's a little slow as it downloads the AWS provider each time — we could fix that checking the binaries for the main GOOS/GOARCH the tests need to support at the cost of increasing the size of the repo.

**Comment by ljfranklin** [comment]
@peterellisjones looks fine to me. Thanks for the PR, this feature should be available on `ljfranklin/terraform-resource:latest` right now!

**Comment by peterellisjones** [comment]
Thanks @ljfranklin

**Pull request merged**
